# Generated by Django 2.2 on 2020-08-27 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
